"""aggiunta campi per audit logging

Revision ID: 4593ef86c208
Revises: 4c13c8d1317e
Create Date: 2026-05-19 12:52:09.456139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4593ef86c208'
down_revision: Union[str, Sequence[str], None] = '4c13c8d1317e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bookings', sa.Column('created_by', sa.String(length=36), nullable=False))
    op.add_column('bookings', sa.Column('last_updated_by', sa.String(length=36), nullable=False))
    op.add_column('room-services', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('room-services', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('room-services', sa.Column('created_by', sa.String(length=36), nullable=False))
    op.add_column('room-services', sa.Column('last_updated_by', sa.String(length=36), nullable=False))
    op.add_column('room_images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('room_images', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('room_images', sa.Column('created_by', sa.String(length=36), nullable=False))
    op.add_column('room_images', sa.Column('last_updated_by', sa.String(length=36), nullable=False))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rooms', sa.Column('created_by', sa.String(length=36), nullable=False))
    op.add_column('rooms', sa.Column('last_updated_by', sa.String(length=36), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_by', sa.String(length=36), nullable=False))
    op.add_column('users', sa.Column('last_updated_by', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('rooms', 'last_updated_by')
    op.drop_column('rooms', 'created_by')
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'created_at')
    op.drop_column('room_images', 'last_updated_by')
    op.drop_column('room_images', 'created_by')
    op.drop_column('room_images', 'updated_at')
    op.drop_column('room_images', 'created_at')
    op.drop_column('room-services', 'last_updated_by')
    op.drop_column('room-services', 'created_by')
    op.drop_column('room-services', 'updated_at')
    op.drop_column('room-services', 'created_at')
    op.drop_column('bookings', 'last_updated_by')
    op.drop_column('bookings', 'created_by')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
