"""modifica campi user

Revision ID: 4c13c8d1317e
Revises: 4e640d5e0691
Create Date: 2026-05-15 14:20:18.232320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c13c8d1317e'
down_revision: Union[str, Sequence[str], None] = '4e640d5e0691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.drop_column('users', 'surname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('surname', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
