"""modificata logica per creare una stanza

Revision ID: 6f7cfb7b64a6
Revises: ecd7d0dd98ae
Create Date: 2026-06-06 16:21:13.730360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f7cfb7b64a6'
down_revision: Union[str, Sequence[str], None] = 'ecd7d0dd98ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_images')
    op.add_column('rooms', sa.Column('number', sa.SmallInteger(), nullable=False))
    op.add_column('rooms', sa.Column('img_url', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'rooms', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'img_url')
    op.drop_column('rooms', 'number')
    op.create_table('room_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('last_updated_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('room_images_room_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('room_images_pkey')),
    sa.UniqueConstraint('url', name=op.f('room_images_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
