"""aggiunto campo enabled alle stanze

Revision ID: b36303dbba32
Revises: 6f7cfb7b64a6
Create Date: 2026-06-20 17:40:43.440390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36303dbba32'
down_revision: Union[str, Sequence[str], None] = '6f7cfb7b64a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'enabled')
    # ### end Alembic commands ###
